### ISSUE TITLE
SEC: https://rdfjs.org

### ISSUE THREAD

**Issue by westurner** [rdfjs/rdfjs.github.io#1]
From public-rdfjs https://lists.w3.org/Archives/Public/public-rdfjs/2015Sep/0021.html :

>    Date: Sat, 12 Sep 2015 09:08:35 -0500
>    Message-ID: <CACfEFw9ZBzQ-tJFCm9QkyN5jc=XeJypB7XLg1_EqtOrXb9cYPA@mail.gmail.com> 
>    To: public-rdfjs@w3.org 
> If you add a CNAME file (e.g. containing 'rdfjs.org'), github will redirect to that domain. You then lose the *.github.io SSL.
> -  [CloudFlare] DNS with SSL for Custom Domains is one way to do HTTPS with github pages and a custom domain.
- "How do I enable free Universal SSL with Github?"
  https://support.cloudflare.com/hc/en-us/articles/203663694-How-do-I-enable-free-Universal-SSL-with-Github-
  - https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

Either:

A. Configure [CloudFlare DNS] with SSL
B. Keep the current HTTP://rdfjs.org links
C. Stay with https://rdfjs.github.io/

**Comment by elf-pavlik** [comment]
:+1: **A**
@l00mi @bergos AFAIK you own _rdfjs.org_, could you please help with resolving his issue?

**Comment by l00mi** [comment]
I have registered and own the domain. I declare it to be part of the [rdfjs W3C](https://www.w3.org/community/rdfjs/) working group, and we are happy to sponsor it for now. If there is any entity representing the W3C group, which can take it over I am also happy to transfer the domain on the spot.

Currently I don't know what the group intends to do with this domain? Was there any discussion which I missed? I would prefer to decide upfront about the usage before investing time in configuration.

If someone likes to go ahead with a CloudFlare SSL setup I am happy to help where needed on the DNS side.

**Comment by westurner** [comment]
> If someone likes to go ahead with a CloudFlare SSL setup I am happy to help where needed on the DNS side.

The CloudFlare SSL setup is described here:
- https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

It's probably appropriate to group DNS and CloudFlare DNS together in terms of roles and responsibilities.

**Comment by westurner** [comment]
Totally dropped the ball here, sorry!

I'd be more than happy to help configure CloudFlare.
- rdfjs.org seems to have expired

https://rdfjs.github.io/
- [ ] Remove `CNAME`
- [ ] Update Link in Project Desc

https://rdfjs.org/
- [ ] Renew DNS
- [ ] Create CloudFlare account
- [ ] Configure CloudFlare SSL; STS
- [ ] Add rdfjs.org record
- [ ] Add www.rdfjs.org
- [ ] Add redirect from/to www.

**Comment by westurner** [comment]
- https://github.com/rdfjs/rdfjs.github.io/commit/14f2f9b0a2f8dd4bfc5127b40d5db4c66d92d6fd
  - README.md table of links

**Comment by elf-pavlik** [comment]
We currently use: https://rdf.js.org/

**Comment by l00mi** [comment]
Yep so we can close this I guess?

BTW we also forward http://rdfjs.org to https://rdf.js.org/
