### ISSUE TITLE
Indicate that @rdfjs/dataset only implements DatasetCore

### ISSUE THREAD

**Issue by alexkreidler** [rdfjs/rdfjs.github.io#12]
Right now the site indicates that it implements Dataset, which it [clearly doesn't](https://github.com/rdfjs-base/dataset/blob/master/DatasetCore.js). This may mislead new users.

**Comment by bergos** [comment]
It implements all non-experimental interfaces. I think that should be enough and it could be even more confusing the other way round when there are changes that look like major version changes but are actually allowed because of the experimental status.

**Comment by alexkreidler** [comment]
That makes sense. I guess a source of my confusion is that `RDF/JS: Dataset specification 1.0` contains `DatasetCore` and `Dataset`, which is experimental. However, when it is referred to as simply Dataset or "the Dataset spec," it can be confusing (e.g. does it refer to the actual Dataset interface?)

Thanks for your response, I'll close this for now.
