### ISSUE TITLE
Request to use logo for rdfjs.vercel.app

### ISSUE THREAD

**Issue by megoth** [rdfjs/rdfjs.github.io#19]
I'm currently working on [rdfjs.vercel.app](https://rdfjs.vercel.app/), a website that aims to document how to use RDF with JavaScript (well, TypeScript and React to be technically correct, but I think the demos should be able to showcase how to use this for "normal" JS as well).

The logo that you've used for your website is very fitting for what I'm trying to convey, and I was hoping that it's ok for me to reuse it for my website?

Also, I realize that rdfjs.vercel.app might be confusingly close to rdf.js.org, so I want to formally ask you whether it's ok for me to use the URL, or if I should find something else? I started the project as semtechjs-demo.vercel.app, but that's kinda clonky and not easy to remember, so I changed it to rdfjs.vercel.app, that at least somewhat rolls of your tongue.

**Comment by elf-pavlik** [comment]
I see no issue with re-using the logo. I see you already have a prominent link to rdf.js.org which should make the distinction clear.
Don't hesitate to PR a new section to rdf.js.org which would link to rdfjs.vercel.app and other educational materials!

**Comment by rubensworks** [comment]
Hi @megoth 👋 
Looks like a great initiative!

The only potential issue I see is the subjective nature of the scores that are given to tools.
This might cause confusion among readers, as the RDF/JS CG is a community-effort, while the scores are not part of this community effort.

**Comment by megoth** [comment]
> The only potential issue I see is the subjective nature of the scores that are given to tools. This might cause confusion among readers, as the RDF/JS CG is a community-effort, while the scores are not part of this community effort.

Yes, I recognize this, which is why I try to be very explicit with contextualization (e.g. having the title "My review of [x]"). 

As a sidenote: I hope to introduce a community review feature on future versions of the website (hence why I asked for [help on the forum](https://forum.solidproject.org/t/good-vocabularies-for-reviews-and-ratings/6989)), where others can post reviews as well, at which point I'll change the review section for a library to reflect multiple reviews from the community (where mine is just one of many).

**Comment by megoth** [comment]
But I can add a prominent message that makes it clear that this is a personal website, and not to be confused with the RDF/JS CG.

**Comment by megoth** [comment]
I've updated the website with the logo. I've also added a disclaimer to all reviews that make it clear that this is personal assessment. An example can be seen at the [review for rdflib.js](https://rdfjs.vercel.app/rdflib#review).

I reckon if everything looks ok, that we can close this issue? (I'll close this myself in a week or so if noone objects.)

(If anyone want to give me feedback on the website, I'm all ears ^_^ I'll read the feedback here, or you can send me a DM or [add an issue on the project's GH page](https://github.com/megoth/rdfjs/issues).)

**Comment by rubensworks** [comment]
Looks great to me @megoth, nice work! 👏

**Comment by bergos** [comment]
Nice work @megoth! This issue reminded me to add my libraries to the list and add a simple sort/filter feature, which I wanted to add for a while.

There is [documentation section](https://github.com/rdfjs/rdfjs.github.io/blob/84f7354747ff00d62667cf80d62bc3c6347d43b6/index.html#L47-L48) on the page, which is currently hidden because it doesn't contain any items. We didn't discuss yet what it should contain, but maybe it could include a link to your page. I will open an issue for that topic.

**Comment by megoth** [comment]
I'm closing this issue as I think it's been resolved.
