### ISSUE TITLE
Content not rendering on http://rdf.js.org/

### ISSUE THREAD

**Issue by joepio** [rdfjs/rdfjs.github.io#7]
```
{{ specification.name }}
{{ specification.description }}
```
Renders as plaintext:

<img width="857" alt="Screenshot 2019-10-14 at 16 50 23" src="https://user-images.githubusercontent.com/2183313/66760625-c93f6b00-eea2-11e9-9aa7-3416ec26ec1a.png">

**Comment by rubensworks** [comment]
Do you have JavaScript enabled? Seems to work fine for me.

**Comment by l00mi** [comment]
We do expect consumers of the RDF **JavaScript** Libraries to have JavaScript enabled in the browser.
